### PR TITLE
DRAFT: Doc updates: TFSID:1362792 VizAPI custom title field; Tableau Exchange changes, misc edits

### PR DESCRIPTION
**Pull request by d45**
Updates to the documentation to fix:

- VizAPI custom title doc bug
- Tableau Exchange (rebranding)
- Various doc fixes found by @bcantoni

### CODE REVIEW

**Comment by d45** [comment]
All I want to do is a simple update to the docs, but there are two months of commits to `dev` that are also included. 
Should we move the docs to another branch (say, `gh-pages`), so that the doc updates can proceed?

**Comment by johnDance** [comment]
> @alicemhsiao @bcantoni @johnDance @seanmakesgames All I want to do is a simple update to the docs, but there are two months of commits to `dev` that are also included. Should we move the docs to another branch (say, `gh-pages`), so that the doc updates can proceed?

Let's merge down from main. I'm guessing many of those changes are already in main, and then merge up from dev to main. @seanmakesgames , sound like a plan?

**Comment by seanmakesgames** [comment]
> > @alicemhsiao @bcantoni @johnDance @seanmakesgames All I want to do is a simple update to the docs, but there are two months of commits to `dev` that are also included. Should we move the docs to another branch (say, `gh-pages`), so that the doc updates can proceed?
> 
> Let's merge down from main. I'm guessing many of those changes are already in main, and then merge up from dev to main. @seanmakesgames , sound like a plan?

cc @d45 
Yes -- just make this PR off of main and merge there directly. We can and will / should merge from main into dev.

**Comment by seanmakesgames** [comment]
Hm. Maybe I don't understand the situation exactly. Let's get on a call and sort it out.

**Comment by seanmakesgames** [comment]
Closing this PR-- we'll do a release of dev next week and it should capture these changes.

**Pull request closed without merging**
