### PR TITLE
fix audit

### PR DESCRIPTION
**Pull request by seanmakesgames**

### CODE REVIEW

**Review by shinchris — COMMENTED** [review]
Was this generated by running `npm update`?
Also is the intention here to fix all of the dependabot alerts? It looks like there are a few left.

**Comment by seanmakesgames** [comment]
> Was this generated by running `npm update`?
This was done by doing npm audit fix.

> Also is the intention here to fix all of the dependabot alerts? It looks like there are a few left.
Yes. Those alerts won't go away until this change is merged all the way to master. (this PR is off of dev)
After these changes, only two low sev issues remain (checked via npm audit), which is as intended.

**Comment by shinchris** [comment]
Ah okay, asking because ecstatic and eslint were two that I didn't see in the change, but are both set to moderate sev on github. Otherwise looks good!

**Comment by seanmakesgames** [comment]
Good catch -> those were probably sub-dependencies -- would be great if you checked out the branch and ran `npm audit`

**Review by shinchris — APPROVED** [review]
yep, down to 2 low sev issues.

**Pull request merged**
