### PR TITLE
Doc updates for v1.9. Release notes;About Help topic; privacy URL change

### PR DESCRIPTION
**Pull request by d45**
@mwhagedorn @johnDance @alicemhsiao @wescwu 

- Just added release notes (and links to ref pages)
- Added the About Help topic (standard SFDC)
- Updated privacy link to SDFC policy

### CODE REVIEW

**Comment by johnDance** [comment]
@d45, the dashboard team also added more font support. @b-carver can your team provide specifics for Dave?

**Comment by d45** [comment]
@b-carver  Are we talking about the addition of Benton Sans? Thanks.

**Comment by b-carver** [comment]
Yes, we're talking about Benton Sans as well as work for loading all Tableau fonts by default.  Garrett said he'd reply by EOD with more specifics.

**Comment by d45** [comment]
@b-carver @johnDance  I've updated the release notes with the font support announcement. I added a link to the formatting sample. The link will point to the new sample when we merge `dev` to `main`.

**Pull request merged**
